# Generated by Django 4.1 on 2022-09-14 07:29

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ribbon.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to=ribbon.models.section_image_path)),
                ('banner', models.ImageField(upload_to=ribbon.models.section_banner_path)),
                ('banner_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('subscribers', models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('moderators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('section_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ribbon.section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ribbon.models.sectionpost_path)),
                ('content', models.TextField(blank=True, max_length=4000)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ribbon.section')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(max_length=500)),
                ('rating', models.IntegerField(default=0, editable=False)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('section_post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ribbon.sectionpost')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
