# Generated by Django 4.1 on 2022-10-13 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ribbon.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to=ribbon.models.section_image_path)),
                ('banner', models.ImageField(blank=True, upload_to=ribbon.models.section_banner_path)),
                ('banner_color', models.TextField(default='#FFFFFF', max_length=7)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('subscribers', models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ribbon.models.sectionpost_path)),
                ('content', models.TextField(blank=True, max_length=4000)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ribbon.section')),
            ],
            options={
                'ordering': ['-rating', '-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(max_length=500)),
                ('rating', models.IntegerField(default=0, editable=False)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('section_post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ribbon.sectionpost')),
            ],
            options={
                'ordering': ['-rating', 'date_published'],
            },
        ),
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('value', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ribbon.sectionpost')),
            ],
            options={
                'unique_together': {('owner', 'post')},
            },
        ),
        migrations.CreateModel(
            name='CommentReview',
            fields=[
                ('value', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ribbon.comment')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'comment')},
            },
        ),
    ]
