# Generated by Django 4.1 on 2022-09-05 08:12

from django.db import migrations, models
import django.db.models.deletion
import ribbon.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to=ribbon.models.section_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SectionPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to=ribbon.models.sectionpost_path)),
                ('content', models.TextField(max_length=2000)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ribbon.section')),
            ],
        ),
    ]
