# Generated by Django 4.1 on 2022-09-05 08:17

from django.db import migrations, models
import ribbon.models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ribbon.models.sectionpost_path),
        ),
    ]
