# Generated by Django 4.1 on 2022-09-15 14:01

from django.db import migrations, models
import ribbon.models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-rating', 'date_published']},
        ),
        migrations.AlterModelOptions(
            name='sectionpost',
            options={'ordering': ['-rating', '-date_published']},
        ),
        migrations.AlterField(
            model_name='section',
            name='banner',
            field=models.ImageField(blank=True, upload_to=ribbon.models.section_banner_path),
        ),
        migrations.AlterField(
            model_name='sectionpost',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
