# Generated by Django 4.1 on 2022-09-06 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ribbon', '0002_alter_sectionpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
