# Generated by Django 4.1 on 2022-10-01 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('rating', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, default='user/profile/default.png', upload_to='user/profile/')),
                ('banner_image', models.ImageField(blank=True, default='user/banner/default.png', upload_to='user/banner/')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
