# Generated by Django 4.1 on 2022-09-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_image',
            field=models.ImageField(default='banner/default.png', upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
