# Generated by Django 4.1 on 2022-09-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_image',
            field=models.ImageField(blank=True, default='banner/default.png', upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/default.png', upload_to='profile/'),
        ),
    ]
